export const ADD_INGREDIENT = 'ADD_INGERDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_PURCHASING = 'SET_PURCHASING';
export const INIT_BURGER = 'INIT_BURGER';

export const SET_ORDERS = 'SET_ORDERS';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';
export const START_PURCHASE_BURGER = 'START_PURCHASE_BURGER';
